#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Rendezvous
version:      0.86
version_from: lib/Net/Rendezvous.pm
installdirs:  site
requires:
    Net::DNS:                      0.44
    Socket:                        1.75

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
